version: '3.9'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anu2005$
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: Anu2005$
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: anu
    image: quay.io/keycloak/keycloak:13.0.0
    ports:
      - "8081:8080"  # Changed port to 8081 on the host
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
